src/main/java/com/echobox/api/linkedin/types/Address.java
src/main/java/com/echobox/api/linkedin/types/organization/LocationInfo.java
src/main/java/com/echobox/api/linkedin/types/v1/Address.java
src/main/java/com/echobox/api/linkedin/types/v1/CodeAndNameType.java
src/main/java/com/echobox/api/linkedin/types/v1/CodeType.java
src/main/java/com/echobox/api/linkedin/types/v1/Company.java
src/main/java/com/echobox/api/linkedin/types/v1/CompanyType.java
src/main/java/com/echobox/api/linkedin/types/v1/ContactInfo.java
src/main/java/com/echobox/api/linkedin/types/v1/EmployeeCountRange.java
src/main/java/com/echobox/api/linkedin/types/v1/IndustryCode.java
src/main/java/com/echobox/api/linkedin/types/v1/Location.java
src/main/java/com/echobox/api/linkedin/types/v1/Share.java
src/main/java/com/echobox/api/linkedin/types/v1/StatusType.java
src/main/java/com/echobox/api/linkedin/types/v1/StockExchange.java
src/main/java/com/echobox/api/linkedin/types/v1/Update.java
src/test/java/com/echobox/api/linkedin/jsonmapper/DefaultJsonMapperTest.java
src/test/java/com/echobox/api/linkedin/jsonmapper/LinkedInJsonMapperV1Test.java
src/test/java/com/echobox/api/linkedin/jsonmapper/SimpleJSON.java
src/test/java/com/echobox/api/linkedin/types/CompanyTypeTest.java
src/test/java/com/echobox/api/linkedin/types/StatusTypeTest.java

Move LinkedIn V1 into it's own package, created POJOs for share body and response
https://developer.linkedin.com/docs/share-on-linkedin
https://developer.linkedin.com/docs/company-pages#targetting_shares
Enables posting to LinkedIn via V1
Tested with snippet:
```
Content content = new Content("Iccccyyyy",
"Leverage LinkedIn's APIs to maximize engagement",
"https://www.bbc.co.uk/news/world-europe-46386867",
"https://i.ytimg.com/vi/mRf3-JkwqfU/hqdefault.jpg");
Tvalues tvalues = new Tvalues("na");
ShareTarget shareTarget = new ShareTarget(tvalues, "geos");
Targeting targeting = new Targeting(new ShareTargets(shareTarget));
Share share = new Share(content, null, new Visibility("anyone"), targeting);
DefaultLinkedInClient client = new DefaultLinkedInClient([accessToken], Version.V1);
Update …
```

TEC-6582 LinkedIn V1 share response body POJO

---

src/main/java/com/echobox/api/linkedin/connection/v2/UGCShareConnection.java
src/main/java/com/echobox/api/linkedin/types/ugc/Commentary.java
src/main/java/com/echobox/api/linkedin/types/ugc/Distribution.java
src/main/java/com/echobox/api/linkedin/types/ugc/ExternalDistributionChannelType.java
src/main/java/com/echobox/api/linkedin/types/ugc/LifeCycleState.java
src/main/java/com/echobox/api/linkedin/types/ugc/Origin.java
src/main/java/com/echobox/api/linkedin/types/ugc/ResponseContext.java
src/main/java/com/echobox/api/linkedin/types/ugc/ShareContent.java
src/main/java/com/echobox/api/linkedin/types/ugc/ShareMedia.java
src/main/java/com/echobox/api/linkedin/types/ugc/ShareMediaCategory.java
src/main/java/com/echobox/api/linkedin/types/ugc/TargetAudience.java
src/main/java/com/echobox/api/linkedin/types/ugc/UGCShare.java
src/main/java/com/echobox/api/linkedin/types/ugc/ViewContext.java
src/main/java/com/echobox/api/linkedin/types/ugc/Visibility.java
src/test/java/com/echobox/api/linkedin/types/ugc/UGCShareTest.java

- Update all typos UCG -> UGC which should be the correct spelling - duh!
https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/ugc-post-api
Will break any existing external usages of UGC package
The project builds successfully

TEC-7379 Ensure LinkedIn SDK UGC is not a typo

---

src/main/java/com/echobox/api/linkedin/connection/v2/RichMediaConnection.java

Add new upload media method that takes a byte array, so we do not have to rely on files.
N/A
Low, adds new API only
Tested that an image can be uploaded this way.

TEC-7351 Update RichMediaConnection to allow byte array

---

src/main/java/com/echobox/api/linkedin/types/objectype/Locale.java
src/main/java/com/echobox/api/linkedin/types/ugc/TargetAudience.java
src/test/java/com/echobox/api/linkedin/types/ugc/TargetAudienceTest.java
src/test/resources/com.echobox.api.linkedin.jsonmapper/targetAudience.json

Using the @EqualsAndHashCode to generate the equals and hash code method for TargetAudience.
N/A
Small risk as it adds specific implementations for the TargetAudience.
- added some unit tests.

TEC-7375 Equals and Hash methods for TargeAudience

---

src/main/java/com/echobox/api/linkedin/connection/ConnectionBase.java
src/main/java/com/echobox/api/linkedin/types/objectype/Locale.java
src/main/java/com/echobox/api/linkedin/types/ugc/TargetAudience.java
src/main/java/com/echobox/api/linkedin/types/urn/URN.java

Adding setters and serialisation for `TargetAudience` class and all member classes. Also renaming the `getURNEntity` to `resolveUNREntity` to avoid using problems with json serialisation.
N/A
Small risk as it doesn't change any logic
Tested locally with a webservice to make sure the TargetAudience field is converted to json.

TEC-7375 Setters and Serialisable for target audience a

---

src/main/java/com/echobox/api/linkedin/types/organization/AccessControl.java

- Make OrganizationalTarget public - doh!
https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/organization-lookup-api#retrieve-organizations
- Exposes OrganizationalTarget which should have been
- Can call `OrganizationalTarget.getLocalizedName`

TEC-7345 Make OrganizationalTarget public

---

src/main/java/com/echobox/api/linkedin/types/ImageV2Elements.java

Adding extra fields for CroppedImage to get the url .
N/A
small risk as this affects only the cropped image  represantation
With the following script 
```java
public static void main(String[] args) throws Exception {
Base.initialiseDBConnections(Base.DBConnection.DEV_READ_WRITE);
try {
AccountAPIId accountAPIId = new AccountAPIId(10547L);
String id = getLinkedInPageOrgURN(accountAPIId);
Organization pageInfo = getPageInfo(accountAPIId, id);
logger.info(pageInfo.toString());
} finally {
Base.shutdownDBConnections();
}
}
```

TEC-7650 extending cropped images to get the url

---

pom.xml
src/main/java/com/echobox/api/linkedin/types/urn/URN.java
src/main/java/com/echobox/api/linkedin/types/urn/URNEntityType.java
src/test/java/com/echobox/api/linkedin/types/urn/URNTest.java

Adding an extra URNEntityType called UGCPOST
https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/ugc-post-api
Small risk as this is an extra field of the enum URNEntityType
Manually tested

TEC-7801 Add UGCPOST URNEntityType

---

CHANGELOG.md

- Update ChangeLog for releasing 1.0.2 to Maven Central
Not Applicable
- Releasing version 1.0.2 to Maven Central, however 1.0.2-SNAPSHOT has been used in production.
- 1.0.2-SNAPSHOT has been used in production so seems to be working fine

TEC-7834 Update changeLog

---

.github/pull_request_template.md
CHANGELOG.md
README.md
pom.xml

- Uncrement version from 1.0.2 to 1.0.3 for the SNAPSHOT
- Updated instructions on releases in README.md
Not Applicable
- Increment the version in `pom.xml` - nothing else has change din the code so is the same as production
- Able to build the project, no changes to code so behaves the same as in production.
Note: Should be merged after https://github.com/ebx/ebx-linkedin-sdk/pull/51

TEC-7834 Increment version from 1.0.2 to 1.0.3-SNAPSHOT 

---

.travis.yml

Explicitly set the distribution to use as the base image in the travis build.
See https://jira.echobox.com/browse/TEC-8021 for additional details
No additional risk.
Build currently failing.  Explicitly setting distribution details, rather than rely on defaults, is ideal.  This PR will test this.

TEC-8021 Explicitly set build image values in .travis.yml

---

src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
src/test/java/com/echobox/api/linkedin/client/DefaultLinkedInClientTest.java

- Ensure non-error responses do not throw linkedin errors
Not Applicable
- Could fail to extract the response
- Added additional unit tests
- Tested with snippet:
```
OrganizationConnection con = new OrganizationConnection(new DefaultLinkedInClient(authToken));
Organization organization =
con.retrieveOrganization(new URN("urn:li:organization:1234"), null);
```
- [/] Build passes.
- [/] Versioning considered (the version number in this PR is inline with semantic 
- [/] Change log has been updated.

TEC-7956 Ensure non-error responses do not throw linkedin errors

---

CHANGELOG.md
src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java

Getting the content length from the request and add the value in the `Content-Length` header. Zero will be added if no content is provided.
https://docs.microsoft.com/en-us/linkedin/shared/api-guide/concepts/error-handling?context=linkedin/context&trk=eml-mktg-20190826-developer-email-api-updates-august&mcid=6570277612550176769&src=e-eml#411-length-required
A small potential risk is the case where the content length is negative (-1). This indicates that at this point we can't know the length. I have tried to share a post with content length -1 and it worked ok. 
Manually posted share and checked the field was set. In staging we should try to update a page to check post with empty content
```java
public static void main(String[] args) throws GeneralSecurityException, IOException { …
```

TEC-7983 Content Length for post requests

---

CHANGELOG.md
src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
src/test/java/com/echobox/api/linkedin/client/DefaultLinkedInClientTest.java

- Ensure 204 HTTP_NO_CONTENT is not thrown as an error
Not Applicable
- Will not throw an error if 204 http response is returned (but it shouldn't...)
- Added a unit test
- Tested by deleting a UCG Post:
```
UGCShareConnection con = new UGCShareConnection(new DefaultLinkedInClient(authToken,
Version.DEFAULT_VERSION));
con.deleteUGCPost(new URN("urn:li:share:12334"));
```

TEC-7950 Ensure 204 HTTP_NO_CONTENT is not thrown as an error

---

CHANGELOG.md
src/main/java/com/echobox/api/linkedin/types/ugc/ShareMediaCategory.java

- Add new ShareMediaCategory NATIVE_DOCUMENT, URN_REFERENCE, LIVE_VIDEO
[LinkedIn documentation](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/ugc-post-api)
- Should support more types of ShareMediaCategory enums
- Added additional enums and ensure we support LIVE_VIDEO

TEC-8790 Add new ShareMediaCategory 

---

CHANGELOG.md
README.md
src/main/java/com/echobox/api/linkedin/client/paging/V2PagingImpl.java
src/test/java/com/echobox/api/linkedin/client/paging/V2PagingImplTest.java

- Currently LinkedIn API is returning an incorrect number of elements for paginated results. For example there are 15 elements, with an initial size of 10, however LinkedIn has returned 8 results. An interim fix for this would be to continue to the next page until there are no more elements in the result.
https://docs.microsoft.com/en-us/linkedin/shared/api-guide/concepts/pagination?context=linkedin/marketing/context
- Pagination is a core part of the LinkedIn API and affects all responses that are paginated.
- Ran this snippet:
```
OrganizationConnection con = new OrganizationConnection(new DefaultLinkedInClient(authToken));
List<AccessControl> organization = con.fetchMemberOrganizationAccessControl(null,
null, null, null);
```

TEC-9746 Interim fix for Linkedin API pagingation 

---

CHANGELOG.md
src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
src/main/java/com/echobox/api/linkedin/client/paging/V2PagingImpl.java
src/test/java/com/echobox/api/linkedin/client/paging/V2PagingImplTest.java

- Remove autopaging when fetching connection, this should be up to the user to control
- Update V2 paging to handle no paging URL params
https://docs.microsoft.com/en-us/linkedin/shared/api-guide/concepts/pagination?context=linkedin/marketing/context
- Affects retrieving paged data
- Affects LinkedIn quota usage as additional requests are required to get the next/previous paginated data.
- Added additional unit tests
- Tested locally to ensure minimum numnber of calls requested during pagination:
```
DefaultLinkedInClient defaultLinkedInClient = new DefaultLinkedInClient(authToken);
OrganizationConnection con = new OrganizationConnection(defaultLinkedInClient);
List<AccessControl> acl = con.fetchMemberOrganizationAccessControl(null,
null, null, null);
List<ShareStatistic> shareStatistics …
```

TEC-9768 Update V2 pagination to avoid using it unless neccessary

---

CHANGELOG.md
pom.xml
src/main/java/com/echobox/api/linkedin/connection/ConnectionBase.java
src/main/java/com/echobox/api/linkedin/connection/v2/UGCShareConnection.java
src/main/java/com/echobox/api/linkedin/types/UGCPostsSortBy.java

Added sortBy parameter to request to retrieve UGC posts.
None.
Sort order of posts returned might be affected, but should remain constant.
Untested for the moment, as there are no unit tests that actually use this code path, so probably best to test when using the updated sdk on main.

TEC-10202 Ensure retrieving UGC are optionally sorted

---

CHANGELOG.md
src/main/java/com/echobox/api/linkedin/jsonmapper/DefaultJsonMapper.java
src/main/java/com/echobox/api/linkedin/types/assets/RegisterUploadRequestBody.java
src/test/java/com/echobox/api/linkedin/types/assets/RegisterUploadRequestBodyTest.java

- Changed `RegisterUploadRequestBody.supportedUploadMechanism` from `SupportedUploadMechanism ` to `List< SupportedUploadMechanism >`
- Change the deserialization of list to support enums
See https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/vector-asset-api#register-an-upload-for-images
- May impact deserialization from JSON
- Add unit tests
N/A

GH-119 convert supportedUploadMechanism to List

---

CHANGELOG.md
README.md
pom.xml
src/main/java/com/echobox/api/linkedin/connection/v2/OrganizationConnection.java

Release 3.0.1
- Enable organisation brand (showcase pages) to call `OrganizationConnection.retrieveOrganizationFollowerCount` and `OrgnizationConnection. retrieveShareStatistics`
- https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/share-statistics?tabs=http
- https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/organization-lookup-api?tabs=http#retrieve-organization-follower-count
- Release 3.0.1
- N/A

Release 3.0.1

---

CHANGELOG.md
pom.xml

- Move dependencies away from logback-classic and logback-core due to CVE-2017-5929. The dependency `ebx-structuredlogging-sdk` uses ``
https://ossindex.sonatype.org/vulnerability/391196a7-f007-430b-b47f-cd9a3fec6374?component-type=maven&component-name=ch.qos.logback.logback-classic&utm_source=ossindex-client&utm_medium=integration&utm_content=1.7.0
Will update the logging libraries but there's no change in the logging structure after local testing
Ran a local test to ensure logging format remains the same in both v3.0.1 and v3.0.2.
Ran `mvn dependency:tree` to make sure ogback-classic and logback-core 1.2.0 and previous is not used.

TEC-15144 Update logging libraries 

---

CHANGELOG.md
src/main/java/com/echobox/api/linkedin/connection/v2/OrganizationConnection.java
src/main/java/com/echobox/api/linkedin/types/LinkedInIdAndURNType.java
src/main/java/com/echobox/api/linkedin/types/organization/OrganizationBase.java
src/main/java/com/echobox/api/linkedin/types/organization/OrganizationResult.java
src/main/java/com/echobox/api/linkedin/types/organization/PrimaryOrganizationType.java
src/test/java/com/echobox/api/linkedin/types/organization/OrganizationBrandTest.java
src/test/java/com/echobox/api/linkedin/types/organization/OrganizationResultTest.java
src/test/resources/com.echobox.api.linkedin.jsonmapper/organization.json
src/test/resources/com.echobox.api.linkedin.jsonmapper/organizationBrand.json

- Add primaryOrganizationType in OrganizationBase
- Update findOrganizationByVanityName 
- return OrganizationBrand if primaryOrganizationType is BRAND
- return Organization if primaryOrganizationType is NONE or SCHOOL
https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/organization-lookup-api?tabs=http
N/A
- Add support for organization brands
- Modified LinkedInMetaInfo to use new version
```
OrganizationBase normal = LinkedInMetaInfo.getPageInfoByVanityName(linkedInAPI,
"Echobox");
System.out.println(organizationToString(normal));
OrganizationBase showcase = LinkedInMetaInfo.getPageInfoByVanityName(linkedInAPI,
"bio-basketball-brand");
System.out.println(organizationToString(showcase));
OrganizationBase school = …
```

TEC-16773 Update search by vanityName to return instances according to primaryOrganizationType

---

CHANGELOG.md
src/main/java/com/echobox/api/linkedin/util/JsonUtils.java
src/test/java/com/echobox/api/linkedin/util/JsonUtilsTest.java

Fix the `JsonUtils.getValue` to return numeric values if the jsonvalue is a numeric one.
N/A
small as it will make sure we always use a number if the json value is a numeric one
- manually
-  unit test

TEC-16993 Update LinkedInSDK to Handle Json Numbers Correctly

---

.circleci/config.yml

GPG secret key imports & decoding moved to build step where they are required for use by `build.sh` script
N/A
No risks
To be tested on PR merge

SL-2042 Move gpg key imports to build step

---

.circleci/config.yml
buildscripts/build.sh

GPG key imports moved to build.sh to avoid duplication of conditional logic and ensure variables are available to script
N/A
None
Dev build to be tested after PR merge

SL-2042 Move GPG keys logic to build.sh

---

buildscripts/build.sh

Passphrase passed into import of GPG_OWNERTRUST
https://www.gnupg.org/documentation/manuals/gnupg/Operational-GPG-Commands.html
None. Pipeline currently broken anyway
Dev build to be tested after PR merge

SL-2042 Provide passphrase to import ownertrust

---

buildscripts/build.sh

Snapshot versioning logic added to `build.sh` since `- checkout` in new jobs re-sources code from build branch and therefore overwrites version changes conducted in previous steps.
https://circleci.com/docs/configuration-reference#checkout
None
To be tested on PR merge

SL-2042 Ensure dev branch builds only deploy snapshot versions

---

.circleci/config.yml
buildscripts/build.sh

Repeated logic removed from `build-sh`. Snapshot version-setting script recalled before `build.sh`
N/A
None
PR build already tested and successful

SL-2042 Undo duplicated code

---

.circleci/config.yml
pom.xml

Checkout step added to predeploy job to allow invocation of `exportMVNVersionWithSnapshotIfNotARelease.sh`
Named the step which calls the above script
https://circleci.com/docs/configuration-reference#checkout
None. Will allow script to be called so that mvn version can be used in `git tag $DEPLOY_TAG`
To be tested on PR merge to dev

SL-2042 Run checkout step to source code in predeploy job

---

CHANGELOG.md
pom.xml
src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java

Add google-api-client dependency at v2.0.0
Replace deprecated code
N/A
Potentially using code that has been deprecated in the later google-api-client version.
Code compilation and passing unit tests should be sufficient.

Upgrade google-api-client dependency to 2.0.0

---

pom.xml

This reverts commit 1e019d12f036c1976677de9c7be9d127e6bfc951.
Compiles

Revert "Bump checkstyle from 8.45 to 10.3.4 (#196)"

---

CHANGELOG.md
src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java

Previously the request body of a 422 error was swallowed by the response handling code. This ensures that it isn't. The intention is to be able to get to the bottom of the 422 errors we are receiving, this is covered in [this](https://echobox.atlassian.net/browse/SL-2425) investigation.
This should be a patch version change. I will release this change after this PR goes in.
No testing required.

SL-2567 - Include response body when raising an exception following a 422.

---

.circleci/config.yml

`exportMVNVersionWithSnapshotIfNotARelease.sh` called from deploy step, before `build.sh`. This is required to ensure version is set to `SNAPSHOT` before a PR merge to dev deployment.
N/A
None
Tested on a previous config.yaml 
N/A

SL-2607 Export mvn version in same step as build & deploy

---

CHANGELOG.md
src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java

Instead of providing an empty JSON object as the body of the request, we are setting it to null. This ensures that no content type is set by `DefaultWebRequestor::executePost`. I also changed the `DefaultWebRequestor::addHeadersToRequest` to allow to set `application/x-www-form-urlencoded` value for `Content-Type` header (if it has not been set yet).
Note: Although the [documentation](https://docs.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow?context=linkedin%2Fcontext&tabs=HTTPS#step-3-exchange-authorization-code-for-an-access-token) suggests that you need to add a Content-Type header, the request still works without it. I have added the header to comply with the documentation and just in case it stops working in future because the header is missing.
Not …

GH-123 Fixed unable to obtain accessToken

---

CHANGELOG.md
pom.xml

Removed dependency as it wasn't being used. Removes the need for this dependabot PR: https://github.com/ebx/ebx-linkedin-sdk/pull/197
It is silently being used somewhere. See Testing section.
I have compiled the code and run all the tests. I also compiled the `main` repo maven project using this version and ran the Social API.
Please do consider whether this is fully tested!

SL-302 - Remove unused google-api-services-oauth2 dependency.

---

src/main/java/com/echobox/api/linkedin/connection/v2/ShareConnection.java
src/main/java/com/echobox/api/linkedin/types/social/actions/CommentAction.java

This pull requests removes the duplicate count parameter and fixes the owner URNs array param, since they original, unmodified method returned status 403.
[Find shares by owner](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/share-api?tabs=http#find-shares-by-owner)
There should be no risks in my changes. Impact should be very limited since the existing method doesn't work in the first place.
Tests performed in local environment, with test calls. That's how I discovered the issue.

GH-239 fix getShares method

---

src/main/java/com/echobox/api/linkedin/client/DefaultVersionedLinkedInClient.java
src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedOrganizationConnection.java

- Remove `X-Restli-Protocol-Version: 2.0.0` from default headers, as it is found that this endpoint cannot be performed with this
- Add `retrieveOrganizationBrandByParentOrganization `in `VersionedOrganizationConnection`
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/organization-lookup-api?view=li-lms-2022-11&tabs=http#find-administered-organization-brands-by-parent-organization
- Little. It's new function.
- May affect previously developed functions.
- Manually tested with below code snippet.
```
List<OrganizationBrand> organizationsByParent =
organizationConnection.retrieveOrganizationBrandByParentOrganization(
new URN("urn:li:organization:88910959"));
Optional.ofNullable(organizationsByParent).map(Collection::stream).orElseGet(Strea …
```

SL-3755 find organization brand by parent organization URN

---

src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedOrganizationConnection.java

- Add `fetchMemberOrganizationAccessControl()` to `VersionedOrganizationConnection`
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/organization-access-control-by-role?view=li-lms-2022-11&tabs=http#find-a-members-organization-access-control-information
Little. A new endpoint
- Tested with below code snippet
```
List<AccessControl> acl = organizationConnection.fetchMemberOrganizationAccessControl(
"ADMINISTRATOR", "APPROVED", null, null);
Optional.ofNullable(acl).map(Collection::stream).orElseGet(Stream::empty)
```
Result:
```
{"state":"APPROVED","role":"ADMINISTRATOR","roleAssigneeURN":{"entityType":"person","id":"sXD_V6IiPY"},"organizationURN":{"entityType":"organization","id":"88910959"} …
```

SL-3757 add fetchMemberOrganizationAccessControl

---

src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedOrganizationConnection.java

- Add `findOrganizationAccessControl()` to `VersionedOrganizationConnection`
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/organization-access-control-by-role?view=li-lms-2022-11&tabs=http#find-organization-administrators
- Little. A new function
- Tested with below code snippet
```
List<AccessControl> acl = organizationConnection.findOrganizationAccessControl(
new URN("urn:li:organization:88910959"),
"ADMINISTRATOR", "APPROVED", null, null);
Optional.ofNullable(acl).map(Collection::stream).orElseGet(Stream::empty)
```
Result:
```
{"state":"APPROVED","role":"ADMINISTRATOR","roleAssigneeURN":{"entityType":"person","id":"sXD_V6IiPY"},"organizationURN":{"entityType":"organization","id":"889 …
```

SL-3758 add find AccessControl by URN

---

src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java

- Remove the setting of `content-type` header
We need to remove the `content-type` header from being set in `DefaultWebRequestor`. The header is currently being set by `google-http-client` in `HttpRequest` line 980.
With the previous API, it seems LinkedIn did not throw errors based on multiple headers of the same key. However, the new API throws a 400 Bad Request if there are multiple headers of the same key.
Manually tested previous and new API versions locally.

Remove redundant content-type header

---

src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java

- Remove the setting of `content-type` header
We need to remove the `content-type` header from being set in `DefaultWebRequestor`. The header is currently being set by `google-http-client` in `HttpRequest` line 980.
With the previous API, it seems LinkedIn did not throw errors based on multiple headers of the same key. However, the new API throws a 400 Bad Request if there are multiple headers of the same key.
Manually tested previous and new API versions locally.

SL-4002 Remove redundant http header

---

src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedCommentConnection.java
src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedCommentsConnection.java

- Create versioned comments connection class
- Copy `postComment` method from v2 to versioned comments connection class
- Tag v2 comment class as deprecated
Manual testing

SL-3780 Create versioned comments connection

---

src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedPostConnection.java

- Add retrievePostsByAuthor() in VersionedPostConnection
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/posts-api#get-posts-by-urn
- Little. It's new function
- Sorting is not supported for Posts API (it was supported in UGC Posts). Some changes may be required when migration
- It looks like sorted descending by created/published/last modified time
- Manually tested with below code snippet.
```
Connection<Post> postPages = postConnection.retrievePostsByAuthor(bioChemicalURN, 20);
List<Post> posts = postPages.getData();
Optional.ofNullable(posts).map(Collection::stream).orElseGet(Stream::empty)
```
Result:
```
{"author":{"entityType":"organization","id":"19049739"},"createdAt":1672942841425,"publ …
```

SL-3771 retrieve posts by author

---

src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedPostConnection.java

- Add VersionedPostConnection.deletePost()
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/posts-api?view=li-lms-2022-12&tabs=http#delete-posts
Little. New function
Manual testing
```
VersionedLinkedInClient client = new DefaultVersionedLinkedInClient(authToken);
VersionedPostConnection postConnection = new VersionedPostConnection(client);
postConnection.deletePost(new URN("urn:li:share:7017192031940751360"));
```
Checked the post was removed.

SL-3779 Add delete post function to VersionedPostConnection

---

src/main/java/com/echobox/api/linkedin/connection/v2/ShareConnection.java
src/main/java/com/echobox/api/linkedin/connection/v2/UGCShareConnection.java
src/main/java/com/echobox/api/linkedin/types/images/InitializeUploadRequestBody.java
src/test/java/com/echobox/api/linkedin/types/image/ImageUploadTest.java
src/test/java/com/echobox/api/linkedin/types/post/PostTest.java
src/test/resources/com.echobox.api.linkedin.jsonmapper/initializeUpload.json
src/test/resources/com.echobox.api.linkedin.jsonmapper/initializeUploadRequest.json
src/test/resources/com.echobox.api.linkedin.jsonmapper/post.json

- Add unit tests for post and image upload POJOs
- Add no arg constructor to `initializeUploadRequestBody `(and its inner class)
- Deprecate `ShareConnection `& `UGCShareConnection`
N/A
- Should be no. Tests only
- The change itself

SL-3779 add unit tests for post and image upload pojos

---

src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java

- Move `toString` call on array list object to first element in array list (if it only contains one element)
Low - changes to `DefaultWebRequestor` but headers are not being used anywhere currently
Tested manually

SL-4163 Fix response header mapping

---

src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
src/main/java/com/echobox/api/linkedin/client/DefaultVersionedLinkedInClient.java
src/main/java/com/echobox/api/linkedin/connection/v2/ConnectionBaseV2.java
src/main/java/com/echobox/api/linkedin/connection/v2/OrganizationConnection.java

- Update versioning month to the latest `202301`
- Deprecate v2 connection classes
Note: Version bump will be done in subsequent PR.
N/A
- Little. It would be tested again when we use the new version
- Ran some functions and the result is the same as before
```
String vanityName = "bio-chemicals-london";
List<OrganizationBase> organizations =
organizationConnection.findOrganizationByVanityName(vanityName, null,
10);
Organization organization = organizationConnection.retrieveOrganization(
new URN("urn:li:organization:19049739"),null);
String emailDomain = "nike.com";
List<Organization> organizationsByDomain =
organizationConnection.findOrganizationByEmailDomain(emailDomain, null, 10);
```
Generate compare URL from https://github.com/ebx/ebx-linkedin-sdk/compare so that it's easily …

SL-3781 Update versioning month the latest and deprecate v2 connections

---

src/main/java/com/echobox/api/linkedin/util/PostUtils.java

- Add a new utility class (PostUtils) to fill link post data
N/A
No. Just a new method.
Manual testing
```
Distribution distribution = new Distribution(Distribution.FeedDistribution.MAIN_FEED);
String commentary = "Paul George, who missed the previous five games after tweaking a "
+ "hamstring injury, returned to the lineup Tuesday night, but the Clippers fell to their"
+ " eighth loss in 10 games. - from SDK 2";
Post post = new Post(bioChemicalURN, commentary, distribution, Post.LifecycleState.PUBLISHED,
Post.Visibility.PUBLIC);
URN preloadedURN = new URN("urn:li:image:C4D10AQEUTYPZ4rv2_w");
String articleLink = "https://www.espn.co.uk/nba/story/_/id/35469012/george-returns-lineup"
+ "-clippers-play-host-76ers?utm_medium=Social&utm_source=LinkedIn#Echobox=1674039366";
String title = …
```

SL-3777 Add method to fill link post data

---

CHANGELOG.md
src/main/java/com/echobox/api/linkedin/client/DefaultVersionedLinkedInClient.java
src/main/java/com/echobox/api/linkedin/exception/DefaultLinkedInExceptionMapper.java

- Move DefaultLinkedInExceptionMapper to a separate file
- Add constructors for DefaultLinkedInClient to allow custom versioned month
https://github.com/ebx/ebx-linkedin-sdk/issues/275
N/A
Little. Just moving an inner class and adding constructors
N/A

SL-4278 Better support for custom versioned month

---

CHANGELOG.md
src/main/java/com/echobox/api/linkedin/util/JsonUtils.java
src/test/java/com/echobox/api/linkedin/util/JsonUtilsTest.java

- Add boolean support to JsonUtils
https://github.com/ebx/ebx-linkedin-sdk/issues/274
N/A
- Little. Just add support to boolean
- Unit test added

SL-4280 Add boolean support to JsonUtils

---

src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedImageConnection.java
src/main/java/com/echobox/api/linkedin/types/images/ImageDetails.java

- Add `retrieveImageDetails` method in `VersionedImageConnection` class
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/images-api#get-a-single-image
Low
Tested manually:
```
VersionedImageConnection connection = new VersionedImageConnection(client);
ImageDetails imageDetails = connection.retrieveImageDetails(new URN("urn:li:image:C4D10AQFEzD9yKMG1Aw"));
Result:
imageDetails = ImageDetails(owner=urn:li:organization:19049739, id=urn:li:image:C4D10AQFEzD9yKMG1Aw, downloadUrl=https://media.licdn.com/dms/image/C4D10AQFEzD9yKMG1Aw/image-shrink_1280/0/1675696947631?e=1676559600&v=beta&t=m0GVzFrNj203QU_bAS0vD1FKuEEvP2Q4cxvgbofxPoM, downloadUrlExpiresAt=1676559600000, status=AVAILABLE)
```

SL-4610 Implement functionality to retrieve image details

---

src/main/java/com/echobox/api/linkedin/types/images/ImageDetails.java
src/main/java/com/echobox/api/linkedin/types/posts/Post.java

- Add images map to `Post` object
- Add helper methods to retrieve `title` and `description`

SL-4613 Extend post object to contain image details and helper methods

---

CHANGELOG.md
pom.xml
src/main/java/com/echobox/api/linkedin/connection/v2/AssetsConnection.java
src/main/java/com/echobox/api/linkedin/connection/versioned/UploadHelper.java
src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedImageConnection.java
src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedVideoConnection.java
src/main/java/com/echobox/api/linkedin/types/videos/InitializeUploadResponse.java

* Added `thumbnailUploadUrl` field to `InitializeUploadResponse` so we can use it to upload the thumbnail image for a video.
* Created UploadHelper class containing tools for converting files to bytes and uploading files to LinkedIn
* Refactoring
N/A
N/A
* Tested by running the app locally and successfully shared a video to Linked with a thumbnail image

SL-5153 Allow thumbnail image upload

---

CHANGELOG.md
pom.xml
src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java
src/main/java/com/echobox/api/linkedin/client/WebRequestor.java

- Add more data to debug logs
Have run locally resulting in the following output:
```
17/03 15:55:27.292 [00001-main] DEBUG c.e.a.l.client.DefaultWebRequestor - Executing a POST to https://api.linkedin.com/rest/images?action=initializeUpload with  payload: {"initializeUploadRequest":{"owner":"urn:li:organization:19049739"}} and headers: GenericData{classInfo=[accept, accept-encoding, age, authorization, cache-control, content-encoding, content-length, content-md5, content-range, content-type, cookie, date, etag, expires, if-match, if-modified-since, if-none-match, if-range, if-unmodified-since, last-modified, location, mime-version, range, retry-after, user-agent, warning, www-authenticate], {accept-encoding=[gzip], linkedin-version=202211}}.
17/03 15:55:28.232 [00001-main] DEBUG …
```

SL-5141 Add more data to debug log

---

CHANGELOG.md
pom.xml
src/main/java/com/echobox/api/linkedin/types/posts/Post.java
src/main/java/com/echobox/api/linkedin/types/videos/VideoDetails.java

* Added support to retrieve video details from LinkedIn according to the [Sample response of the GET Video Request](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/videos-api?view=li-lms-2023-02&tabs=http):
```
{
"duration": 32066,
"aspectRatioWidth": 16,
"owner": "urn:li:organization:18799005",
"thumbnail": "https://media-exp1.licdn.com/dms/image/C4E10AQGUkQY7trgh-Q/ads-video-thumbnail_720_1280/0/1635274077531?e=2147483647&v=beta&t=_HxpoaXestMGYSqDyziZjUtzDvsp9zOgZvAy9HtVJZw",
"downloadUrlExpiresAt": 1650549600000,
"downloadUrl": "https://dms.licdn.com/playlist/C4E10AQGUkQY7trgh-Q/mp4-720p-30fp-crf28/0/1635274088269?e=2147483647&v=beta&t=tsv3E_sgOT1e7VPGpmrxk6ED7C0W3vwTh9Ui-8mlFZk",
"id": "urn:li:video:C4E10AQGUkQY7trgh-Q", …
```

SL-5263 Add videos to the Post class in LinkedIn SDK

---

src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedVideoConnection.java
src/main/java/com/echobox/api/linkedin/types/videos/VideoDetails.java

This pull requests provides a way to get video details from a video URN. A `VideoDetails` class is also added in order to map the response from LinkedIn. Fixes #314

GH-314 Enable fetching video details

---

.circleci/config.yml

Machine image upgraded to one which supports for maven builds for Java 11 and Java 17 applications
N/A
No concerns
This machine image is currently in use on the tiktok-sdk pipelines which involve compiling to Java 11

SL-5347 Upgrade machine image to support Java 11

---

CHANGELOG.md
src/main/java/com/echobox/api/linkedin/client/DefaultVersionedLinkedInClient.java

Use 202306 as the default version of the LinkedIn API
N/A
Checking through the change logs, there is no supposed breaking changes.
Tested locally using the Echobox App.

SL-6725 Use 202306 as the default version of the LinkedIn API

---

CHANGELOG.md
pom.xml
src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedOrganizationConnection.java

Endpoint /networkSizes has a parameter edgeType that takes a value. Up to and including the 202304 release of the LinkedIn API, the value was `CompanyFollowedByMember`. In the 202305 release, it has been changed to `COMPANY_FOLLOWED_BY_MEMBER`.
I updated the minor version as this is now incompatible with older versions of the linkedIn API. This is not strictly speaking a reason for updating the minor version but thought it highlights the difference.
N/A
N/A
Using the Echobox App

SL-6725 Update /networkSizes parameter value

---

CHANGELOG.md
src/main/java/com/echobox/api/linkedin/types/LinkedInURNIdType.java
src/main/java/com/echobox/api/linkedin/types/posts/Post.java

The Post class already had its own id field, so didn't need to extend the `LinkedInURNIdType` class.
Addresses this issue: https://github.com/ebx/ebx-linkedin-sdk/issues/344
Update CHANGELOG
Minor, have tested locally.
Ran locally and saw that posts could be made and that the log no longer appeared. I had seen it when running with the current latest version of the SDK.
I won't do a specific version release for this change.

SL-9359 - Remove duplicate key in Post object.

---

CHANGELOG.md
README.md
pom.xml
src/main/java/com/echobox/api/linkedin/types/urn/URNEntityType.java

The key namespaces that I wanted to add are `IMAGE` and `DIGITALMEDIAASSET`. This was because an image URN should be input into `ImageConnection.retrieveImageDetails` and digital media assets are what are returned in the logoV2 object, which is an attribute in `Organization` instances. These need to be used in order to get the page profile URL for that organisation.
I added the rest because I saw that they existed, many of these are mentioned here: https://learn.microsoft.com/en-us/linkedin/shared/references/v2/urn-namespace.
Updated CHANGELOG, will do a minor version bump when this PR goes in.
None.

Add additional URN entity types to the URNEntityType enum.

---

CHANGELOG.md
README.md
pom.xml
src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
src/main/java/com/echobox/api/linkedin/connection/OrganizationConnection.java

See commits included.
Changelog updated.
Users wishing to take any version releases after this one will not be able to pass in projections into the updated interfaces, even if they are using older versions. Note though that the previous version (`202306`) is deprecated in June.
Have confirmed that using projection parameters fail when using version `202307`.

Release version 6.0.0

---

CHANGELOG.md
README.md
pom.xml
src/main/java/com/echobox/api/linkedin/connection/OrganizationConnection.java

Previously, only `share` type post URNs were allowed when getting the statistics for individual LinkedIn post. This change
allows `ugcPost` type URNs when retrieving post statistics as well.
n/a
The risks are minimal as there are no breaking changes. It just allows an addition post type to have statistics retrieved.
Tested in calling app.

SL-9774 Add support for ugcPost URNs in the retrieveShareStatistics

---

.circleci/config.yml
CHANGELOG.md
README.md
buildscripts/mvn_verify.sh
pom.xml

The image used to build and deploy from circle ci is updated from ubuntu-2004 to cimg/openjdk:8.0 docker image instead of machine image. This allowed the use of Java 8 to compile while the latest ubuntu machine image uses Java 17.
Also downgraded checkstyle as V10.x+ does not support Java 8.
No need as it only changes the build environment
Minimal
Run the build. The deployment phase can only be tested when a new version is released.

SL-9924 Update CircleCI images

---

CHANGELOG.md
pom.xml
src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java

- Refactor the more straightforward methods, GET and DELETE to use the Java 11 HTTP client
- Used tiktok equivalent [PR](https://github.com/ebx/ebx-tiktok-sdk/commit/a9d37d3080f10a4b4ca1bc84622917708f3717d8#) as base for the changes. Needed to add changes to authorisation so they are in line with linkedin's API requests with `Authorization` header and `Bearer` 
- Changes for PUT and POST requests will come in a follow-up PR
N/A
Risky as it affects all interactions with the LinkedIn API, will be tested thoroughly though.
Tested locally in main (built version `7.1.0` locally and used that) by sharing (GET requests also used here) and deleting a post on LinkedIn without any issues.
versioning requirements). -- I used a minor bump as it is a backwards compatible …

SL-5336 Refactor GET and DELETE requests to use Java 11 HTTP client

---

CHANGELOG.md
CONTRIBUTING.md
README.md
pom.xml

CircleCI is now used for builds. So the readme and contribution notes should reference it.
I followed [these instructions](https://circleci.com/docs/status-badges/) for the status badge. I don't think it will work when the status is [reported](https://app.circleci.com/pipelines/github/ebx/ebx-linkedin-sdk) as unauthorized - it will just show failed in this case. However, the link it is replacing is invalid and always showed that it was passing, so this is making it no worse.
See diff! The status reporting may not be completely accurate, see above.
No code changes.
None.

SL-3087 - Replace references to Travis CI with CircleCI.

---

CHANGELOG.md
README.md
pom.xml
src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java

Updates the version number of the project.
Updates the default LinkedIn API version number to the latest.
Updates the project documentation.
N/A
the only risk is in updating the default LinkedIn API version and that can be overridden by the caller.
Ran the unit tests and tested against the Echobox.

SL-9350 Fix up before release including updating the default API version
