- .gitignore
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
Update the initial documentation
N/A
None
N/A
> TEC-6354 simple documentation

- src/main/java/com/echobox/api/linkedin/client/BaseLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/connection/ConnectionBase.java
- src/main/java/com/echobox/api/linkedin/connection/OrganizationConnection.java
- src/main/java/com/echobox/api/linkedin/types/TimeInterval.java
- src/main/java/com/echobox/api/linkedin/types/TimeRange.java
- src/main/java/com/echobox/api/linkedin/types/organization/AccessControl.java
- src/main/java/com/echobox/api/linkedin/types/organization/OrganizationRole.java
- src/main/java/com/echobox/api/linkedin/util/ValidationUtils.java
Added Organization operations in a wrapper class `OrganizationConnection` for only the minimal operations needed. 
Happy to discuss if any have been missed out
https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations
This will be the main entry point with interacting with the LinkedIn Organization API
Ran each method to ensure parameters and URL are formatted correctly.
Do not have direct access to V2 so will need to be retested once we have been granted access.
> TEC-4765 create linkedin organisation operations

- CodeStyle/checkstyle.xml
- pom.xml
- src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/exception/LinkedInAPIException.java
- src/main/java/com/echobox/api/linkedin/types/social/actions/CommentAction.java
- src/main/java/com/echobox/api/linkedin/types/social/actions/CommentsSummary.java
- src/main/java/com/echobox/api/linkedin/types/social/actions/LikeAction.java
- src/main/java/com/echobox/api/linkedin/types/social/actions/LikesSummary.java
- src/main/java/com/echobox/api/linkedin/types/statistics/CountByAssociationType.java
- src/main/java/com/echobox/api/linkedin/types/statistics/CountByFunction.java
- src/main/java/com/echobox/api/linkedin/types/statistics/CountByIndustry.java
- src/main/java/com/echobox/api/linkedin/types/statistics/CountBySeniority.java
- src/main/java/com/echobox/api/linkedin/types/statistics/CountByStaffCountRange.java
- src/main/java/com/echobox/api/linkedin/types/statistics/FollowerCount.java
- src/main/java/com/echobox/api/linkedin/types/statistics/OrganizationFollowerStatistics.java
- src/main/java/com/echobox/api/linkedin/types/statistics/OrganizationFollowerStatisticsElement.java
- src/test/java/com/echobox/api/linkedin/types/engagement/ShareStatisticsTest.java
- src/test/java/com/echobox/api/linkedin/types/statistics/StatisticsTest.java
- Update checkstyle to version 8.18 and fix updated checkstyle rules
Not Applicable
- Pom has been updated com.puppycrawl.tools:checkstyle 8.18
- Ran a build with new checkstyle rules
> TEC-7114 Update checkstyle version

- .travis.yml
- pom.xml
Following the Travis guide at https://www.phillip-kruger.com/post/continuous_integration_to_maven_central/ this PR makes the necessary changes to create a snapshot release on Github with each build. The .travis.yml file contains a 'secure' key but this is encrypted and only readable by Travis (https://docs.travis-ci.com/user/encryption-keys/).
NA
NA
This PR and the subsequent merge will represent the test.
> TEC-7115 Initial snapshot release to Github configuration.

- .maven.xml
- .travis.yml
- README.md
- pom.xml
Following the Travis guide at https://www.phillip-kruger.com/post/continuous_integration_to_maven_central/ this PR makes the necessary changes to attempt an auto release to maven central of the build artifacts. 
This PR duplicates #28 as that wasn't being picked up by travis.
NA
NA
Needs to be merged to be tested!
NA
> TEC-7115 Release SDK to maven central

- .maven.xml
- .travis.yml
- CONTRIBUTING.md
- README.md
- pom.xml
Following the Travis guide at https://www.phillip-kruger.com/post/continuous_integration_to_maven_central/ this PR makes the necessary changes to attempt an auto release to maven central of the build artifacts. 
Take 3.
NA
NA
Needs to be merged to be tested!
> TEC-7115 Release SDK versions to maven central

- .maven.xml
- .travis.yml
- CONTRIBUTING.md
- README.md
- pom.xml
Releasing v1.0.0 which should also get included in maven central.
NA
Low. The snapshot deployments are now working so we expect the maven central release to also work successfully.
We've ensured the snapshot is correctly released.
> TEC-7115 Release v1.0.0

- .travis.yml
- CONTRIBUTING.md
- README.md
- buildscripts/build.sh
- buildscripts/exportMVNVersionWithSnapshotIfNotARelease.sh
- buildscripts/setToSnapshotIfNotARelease.sh
- buildscripts/validateBuild.sh
* Add the full release badges to the README.md.
* Ensure we change the build version right at the beginning.
* Fix the PR title check
* Move the extended bash scripts into external files
NA
Low as we're just cleaning up docs and the build process.
NA
> TEC-7241 Linked-In SDK Cleanup

- src/main/java/com/echobox/api/linkedin/types/urn/URN.java
Add no-arg constructor to URN class, this is so that it can be serialised/deserialised to Mongo DB without further updates.
N/A
None, providing it compiles.
Tested by compiler
> TEC-7349 Ensure URN has no arg constructor

- src/main/java/com/echobox/api/linkedin/types/organization/Organization.java
- src/test/java/com/echobox/api/linkedin/types/organization/OrganizationTest.java
- src/test/resources/com.echobox.api.linkedin.jsonmapper/organization.json
Changing the `Organization` field `overviewPhotov2` to `overviewPhotoV2`
N/A
Small risk as the change affects only a field.
> TEC-7520 from overviewPhotov2 to overviewPhotoV2

- src/main/java/com/echobox/api/linkedin/types/Address.java
- src/main/java/com/echobox/api/linkedin/types/objectype/Locale.java
- src/main/java/com/echobox/api/linkedin/types/urn/URN.java
Adding toSting methods for `Address` and `Locale`
N/A
Small risk as we add toString implementation
Tested with unit tests in main
> TEC-7362  LinkedIn Social Data Cache

- src/main/java/com/echobox/api/linkedin/types/engagement/TotalShareStatistics.java
- src/test/java/com/echobox/api/linkedin/types/engagement/ShareStatisticsTest.java
Make public TotalShareStatistics and add uniqueImpressionsCount field
N/A
Small risk 
extend the unit test
> TEC-7360 Make public TotalShareStatistics and add uniqueImpressionsCount field

- CHANGELOG.md
- src/main/java/com/echobox/api/linkedin/connection/v2/AssetsConnection.java
- src/main/java/com/echobox/api/linkedin/connection/v2/ConnectionBaseV2.java
- src/main/java/com/echobox/api/linkedin/connection/v2/RichMediaConnection.java
- src/main/java/com/echobox/api/linkedin/types/assets/RegisterUploadRequestBody.java
- Update Assets connection to support image asset uploads (for both file and bytes).
- Deprecate existing `RichMediaConnection` as this will be superseded by the images assets API.
https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/vector-asset-api#upload-the-image
- Will implement uploading images to LinkedIn Assets API. 
- Deprecating existing `RichMediaConnection`.
```
AssetsConnection con = new AssetsConnection(new DefaultLinkedInClient(authToken,
Version.DEFAULT_VERSION));
RegisterUploadRequestBody.ServiceRelationships serviceRelationships =
new RegisterUploadRequestBody.ServiceRelationships(AssetsConnection.SERVICE_RELATIONSHIPS_IDENTIFIER, RelationshipType.OWNER);
RegisterUploadRequestBody.RegisterUploadRequest registerUploadRequest =
new …
```
> TEC-8444 update AssetsConnection with upload image

- CHANGELOG.md
- README.md
Update last stable version to 1.0.3
n/a
n/a
n/a
- [x ] Build passes.
- [ x] Versioning considered (the version number in this PR is inline with semantic 
- [ x] Change log has been updated.
> readme should mention last stable version as 1.0.3

- CHANGELOG.md
- pom.xml
Reverse the change from 1.0.3 to 1.0.4 in pom.xml as it is breaking the dev pipeline. 
None
None
Not fully
> TEC-8021 Reverse the change as it is breaking the dev pipeline

- CHANGELOG.md
- pom.xml
Bump version from 1.0.3 to 1.04
N/A
Small risk as no logic is changed.
locally `mvn clean install`
> TEC-9519 move to from 1.0.3 to 1.0.4

- pom.xml
revert to 1.0.3 until we release then it should be moved to …
N/A
Small risk as this reverts the version
mvn clean install
> TEC-9519: revert to 1.0.3 

- CHANGELOG.md
- pom.xml
New version
User version 1.0.4
Small risk
mvn clean install
> TEC-9519 New version 1.0.4

- CHANGELOG.md
Updates to changelog ready for release
N/A
Changelog only
N/A
N/A
> TEC-9746 Update CHANGELOG.md

- CHANGELOG.md
Revert bad date change in CHANGELOG.md that has happened in the dev branch somehow
N/A
N/A
N/A
N/A
> TEC-9746 Revert bad date change in CHANGELOG.md

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/client/paging/V2PagingImpl.java
- src/test/java/com/echobox/api/linkedin/client/paging/V2PagingImplTest.java
Release 1.0.4
See changelog
See changelog
N/A
N/A
> Release 1.0.4

- README.md
- pom.xml
Post release version bump
N/A
Low
N/A
N/A
> TEC-9746 Bump version to 1.0.5

- README.md
- pom.xml
- Bump development from 1.0.5 to 1.0.6
N/A
Low
N/A
> bump version from 1.0.5 to 1.0.6

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/client/paging/V2PagingImpl.java
- src/test/java/com/echobox/api/linkedin/client/paging/V2PagingImplTest.java
Release 1.0.5
See Changelog
See Changelog
N/A
> Release 1.0.5

- CHANGELOG.md
- README.md
- pom.xml
- Bump version 1.0.6 to 1.0.7
- Update readme and changelog
N/A
N/A
N/A
> Bump dev from version 1.0.6 to 1.0.7

- CHANGELOG.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/connection/v2/OrganizationConnection.java
- src/main/java/com/echobox/api/linkedin/types/organization/Organization.java
- src/main/java/com/echobox/api/linkedin/types/organization/OrganizationBase.java
- src/main/java/com/echobox/api/linkedin/types/organization/OrganizationBrand.java
- src/main/java/com/echobox/api/linkedin/types/urn/URNEntityType.java
- src/test/java/com/echobox/api/linkedin/types/organization/OrganizationBrandTest.java
- src/test/resources/com.echobox.api.linkedin.jsonmapper/organizationBrand.json
Update LinkedIn SDK to include new organization brand page endpoints
https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/organization-lookup-api#retrieve-organization-brands
https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/organization-lookup-api#retrieve-organization-brands
small risk as this is not yet used.
```java
static final Parameter ALL_ORGANISATION_BRANDS_FIELDS = Parameter.with("projection",
"(id,$URN,alternativeNames,coverPhoto,coverPhotoV2,defaultLocale,description,"
+ "foundedOn,industries,localizedDescription,localizedName,"
+ "localizedSpecialties,name,"
+ "parentRelationship,vanityName,versionTag,website,"
+ "logo,logoV2(original~:playableStreams)"
+ …
```
> TEC-10528 Update LinkedIn SDK to include new organization brand page endpoints

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/client/paging/V2PagingImpl.java
- src/main/java/com/echobox/api/linkedin/connection/v2/OrganizationConnection.java
- src/main/java/com/echobox/api/linkedin/types/organization/Organization.java
- src/main/java/com/echobox/api/linkedin/types/organization/OrganizationBase.java
- src/main/java/com/echobox/api/linkedin/types/organization/OrganizationBrand.java
- src/main/java/com/echobox/api/linkedin/types/urn/URNEntityType.java
- src/test/java/com/echobox/api/linkedin/client/paging/V2PagingImplTest.java
- src/test/java/com/echobox/api/linkedin/types/organization/OrganizationBrandTest.java
- src/test/resources/com.echobox.api.linkedin.jsonmapper/organizationBrand.json
Merging dev to master
N/A
Small risk as this is a release
N/A
> Release To Maven  1.0.9 version

- pom.xml
Update pom to version 1.0.9 after release
N/A
No risk
N/A
> TEC-10528 new version

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/jsonmapper/DefaultJsonMapper.java
- src/main/java/com/echobox/api/linkedin/types/assets/RegisterUploadRequestBody.java
- src/test/java/com/echobox/api/linkedin/types/assets/RegisterUploadRequestBodyTest.java
Release version 2.0.1.
- RegisterUploadRequestBody.supportedUploadMechanism should be a list
N/A
- Affects uploading images, although this is not a required field for uploading images.
- Have tested the flow of uploading an image with a supportedUploadMechanism
> Release 2.0.1 version

- CHANGELOG.md
- README.md
- pom.xml
Bump dev to 2.0.2 for development
- N/A
- New version
> Update dev to 2.0.2 development

- CHANGELOG.md
- README.md
- pom.xml
- Bump for next release 3.0.2
- N/A
- New release
> TEC-15066 Bump for next release 3.0.2

- README.md
- pom.xml
- Bump for version 3.0.3 release
- N/A
- Next release
> TEC-15144 Bump for next version release 3.0.3

- README.md
- pom.xml
- Bump for version 3.0.4 release
- N/A
- Next release
> TEC-16773 Bump version for next release

- CHANGELOG.md
- README.md
- pom.xml
Bump version to 3.0.5
Have also improved the documentation around merging PRs and deployments
N/A
N/A
N/A
> TEC-16993 Bump version for next release

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/types/social/actions/CommentAction.java
- src/test/java/com/echobox/api/linkedin/types/social/actions/CommentActionTest.java
- src/test/resources/com.echobox.api.linkedin.jsonmapper/ugcShareWithMentions.json
AttributedEntity added to CommentAction to fix bug where mention attributes couldn't be mapped by DefaultJsonMapper because of multiple 'value' annotations.
None
Release 3.0.5
NA
> Release 3.0.5

- README.md
- pom.xml
Bump version for next release
N/A
N/A
N/A
N/A
> TEC-17104 Bump version for next release

- .circleci/config.yml
- buildscripts/build.sh
- buildscripts/exportMVNVersionWithSnapshotIfNotARelease.sh
- buildscripts/validateBuild.sh
New config yml for Circle CI
https://circleci.com/docs/migrating-from-travis
Deployment pipeline currently already broken. No risks
To be tested after Travis CI integration connection
> SL-2042 Migrate Travis CI to Circle CI new config yml

- .circleci/config.yml
Removed cross-workflow dependency. Success of build step can't be seen by predeploy step as they are now in separate workflows
N/A
Unbreaks Circle CI workflow 
To be tested on merge
> SL-2042 Remove dependency on separate workflow

- .circleci/config.yml
GPG_SECRET_KEYS updated in circle
N/A
N/A
N/A
N/A
> SL-2042 Fix GPG key imports

- .circleci/config.yml
Conditionally import GPG keys only for dev/master build
N/A
None
Dev build to be tested on merge
N/A
> SL-2042 Fix GPG secret key import

- .maven.xml
Secret variable names in `.maven.xml` updated to match variable names in Circle CI Context 
N/A
None
Dev build to be tested on PR merge
> SL-2042 Ensure variables in .maven.xml match var names in context

- README.md
Readme fix
N/A
- Just readme
N/A
> SL-1778 Fix readme

- CHANGELOG.md
- pom.xml
Bump version for next release
N/A
N/A
N/A
> SL-1778 Bump version for next release

- CHANGELOG.md
Changelog of release 3.1.1
N/A
None
N/A
> SL-2327 Update change log release date of 3.1.1

- CHANGELOG.md
- README.md
- pom.xml
- Update readme (for PR from `dev `to `master`)
- Bump version for next release
N/A
Should be none
N/A
> SL-2306 Update readme and bump version for next release

- .github/dependabot.yml
See PR title.
- not required
- not required
> SL-2155 - Update dependabot config do that PRs are only raised weekly and patch versions are ignored.

- CHANGELOG.md
- README.md
- pom.xml
> SL-2567 - Update readme and changelog and bump version for next release

- .circleci/config.yml
Workflow steps consolidated and renamed.
N/A
No risks
Tested in PR build - see bottom of PR
N/A
> SL-2607 Clean up and rename circle ci pipeline steps

- src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java
- Fix stylecheck issue
N/A
Little
Build successful
> SL-2710 Fix stylecheck

- .circleci/config.yml
- .github/dependabot.yml
- .lift.toml
- CHANGELOG.md
- README.md
- buildscripts/validateBuild.sh
- pom.xml
- src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java
- Dependabot change: [Bump maven-gpg-plugin from 1.6 to 3.0.1](https://github.com/ebx/ebx-linkedin-sdk/commit/eb883d438c93c3a94d8c3cca18d8b467863b7434)
- [Fixed unable to obtain accessToken (](https://github.com/ebx/ebx-linkedin-sdk/commit/8c2b218c14ba52fccb53758c672667250ca5e3f0)https://github.com/ebx/ebx-linkedin-sdk/pull/135[)](https://github.com/ebx/ebx-linkedin-sdk/commit/8c2b218c14ba52fccb53758c672667250ca5e3f0)
N/A
Release 3.1.3
N/A
> Release 3.1.3

- CHANGELOG.md
- README.md
- pom.xml
Updated readme and changelog and bumped version for next release
Not Applicable
No risks
Not Applicable
> GH-123 - Update readme and changelog and bump version for next release

- CHANGELOG.md
Update change log for the changes (dependencies and https://github.com/ebx/ebx-linkedin-sdk/pull/144)
N/A
N/A
N/A
> SL-2764 Update change log

- CHANGELOG.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java
- src/main/java/com/echobox/api/linkedin/connection/v2/ShareConnection.java
- src/main/java/com/echobox/api/linkedin/types/social/actions/CommentAction.java
Dependabot changes:
slf4j 
google-api-services-oauth2
sevntu-checks
Fixed getShares:
https://github.com/ebx/ebx-linkedin-sdk/pull/144
N/A
Release 3.1.4
N/A
> Release 3.1.4

- CHANGELOG.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java
- src/main/java/com/echobox/api/linkedin/connection/v2/ShareConnection.java
- src/main/java/com/echobox/api/linkedin/types/social/actions/CommentAction.java
- Merge dev to master again after https://github.com/ebx/ebx-linkedin-sdk/pull/241 is squashed
> Merge dev to master to fix branch issue

- CHANGELOG.md
- README.md
- pom.xml
Bump version for next release
N/A
N/A
N/A
> SL-2764 Bump version for next release

- src/main/java/com/echobox/api/linkedin/client/VersionedLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/version/Version.java
- src/test/java/com/echobox/api/linkedin/client/VersionedLinkedInClientTest.java
- Created VersionedLinkedInClient (copied from DefaultLinkedInClient, with a little bit refactoring)
N/A
- It's not in use yet.
N/A
Change log and version will be updated when migration is completed
> SL-3749 Create new LinkedIn client for versioned API

- src/main/java/com/echobox/api/linkedin/client/VersionedLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/connection/v2/OrganizationConnection.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedOrganizationConnection.java
- New organization connection class for versioned API
- Migrated method of get by vanity name
- Send HTTP headers for GET and DELETE requests.
N/A
Little. New endpoint.
- Setup VersionedLinkedInClient and call get by vanity name method
```
VersionedLinkedInClient client = new VersionedLinkedInClient(authToken);
VersionedOrganizationConnection organizationConnection =
new VersionedOrganizationConnection(client);
List<OrganizationBase> organizations =
organizationConnection.findOrganizationByVanityName(vanityName, null,
10);
Optional.ofNullable(organizations).map(Collection::stream).orElseGet(Stream::empty)
```
Result:
`{"localizedWebsite":"http://jobs.nike.com/","locations":[{"staffCountRange":"SIZE_1","locationType":"HEADQUARTERS","address": …
> SL-3752 Create organization connection and get by vanity name method

- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedOrganizationConnection.java
- Migrate retrieveOrganization from OrganizationConnection
N/A
Little. It's new function
Tested by below code snippet:
```
Organization organization = organizationConnection.retrieveOrganization(
new URN("urn:li:organization:19049739"),null);
System.out.println(gson.toJson(organization));
```
Result:
`{"groups":[],"locations":[],"specialties":[],"staffCountRange":"SIZE_2_TO_10","organizationType":"PRIVATELY_HELD","alternativeNames":[],"coverPhotoV2":{"cropInfo":{"height":399,"width":2361,"xAxis":0,"yAxis":344},"cropped":{"entityType":"digitalmediaAsset","id":"C4D1BAQFgCqhqWC1tFg"},"original":{"entityType":"digitalmediaAsset","id":"C4D1BAQFgCqhqWC1tFg"}},"defaultLocale":{"country":"US","language":"en"},"industries":[{"entityType":"industry","id":"54"}],"localizedName":"Bio Chemicals …
> SL-3753 Migrate retrieveOrganization

- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedImageConnection.java
- src/main/java/com/echobox/api/linkedin/types/images/InitializeUpload.java
- src/main/java/com/echobox/api/linkedin/types/images/InitializeUploadRequestBody.java
- Create ImagesConnection class
- Create request/response objects
> SL-3768 Create images connection with request/response

- src/main/java/com/echobox/api/linkedin/client/DefaultVersionedLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedOrganizationConnection.java
- Add findOrganizationByEmailDomain in VersionedOrganizationConnection
- Move required headers to the constructor of DefaultVersionedLinkedInClient
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/organization-lookup-api?view=li-lms-2022-11&tabs=http#find-organization-by-email-domain
- Little. Not in use yet.
- Manually tested with below code snippet
```
List<Organization> organizations =
organizationConnection.findOrganizationByEmailDomain(emailDomain, null, 10);
Optional.ofNullable(organizations).map(Collection::stream).orElseGet(Stream::empty)
```
Result:
```
{"locations":[{"staffCountRange":"SIZE_11_TO_50","locationType":"HEADQUARTERS","address":{"country":"US","line1":"NYC","city":"NY" …
```
> SL-3754 Add retrieve organization by email domain

- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedOrganizationConnection.java
- Add `retrieveOrganizationBrand()` to `VersionedOrganizationConnection`
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/organization-lookup-api?view=li-lms-2022-11&tabs=http#retrieve-an-administered-organization-brand
Little. New endpoint.
- Tested with below code snippet
```
OrganizationBrand brand = organizationConnection.retrieveOrganizationBrand(
new URN("urn:li:organizationBrand:88912973"), null);
System.out.println(gson.toJson(brand));
```
Result:
```
{"autoCreated":false,"alternativeNames":[],"defaultLocale":{"country":"US","language":"en"},"industries":[{"entityType":"industry","id":"33"}],"localizedName":"Ewok Running Brand","localizedSpecialties":[],"name":{"localized":{"en_US":"Ewok Running …
```
> SL-3756 Find organization brand by URN

- src/main/java/com/echobox/api/linkedin/connection/v2/ConnectionBaseV2.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedConnection.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedOrganizationConnection.java
- Add `retrieveOrganizationFollowerStatistics `and `retrieveOrganizationPageStatistics`
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/follower-statistics?view=li-lms-2022-11&tabs=http#retrieve-lifetime-follower-statistics
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/follower-statistics?view=li-lms-2022-11&tabs=http#retrieve-time-bound-follower-statistics
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/page-statistics?view=li-lms-2022-11&tabs=http#retrieve-lifetime-organization-page-statistics
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/page-statistics?view=li-lms-2022-11&t …
> SL-3759 Add followers page stats

- src/main/java/com/echobox/api/linkedin/connection/v2/AssetsConnection.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedImageConnection.java
- src/main/java/com/echobox/api/linkedin/util/ValidationUtils.java
- Implement methods to call Images API endpoint to upload image
- Extract common response validation into `ValidationUtils` class
Manual testing
> SL-3769 Implement image upload functionality

- src/main/java/com/echobox/api/linkedin/client/DefaultVersionedLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java
- src/main/java/com/echobox/api/linkedin/connection/v2/AssetsConnection.java
- src/main/java/com/echobox/api/linkedin/connection/v2/ConnectionBaseV2.java
- src/main/java/com/echobox/api/linkedin/connection/v2/OrganizationConnection.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedCommentConnection.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedConnection.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedImageConnection.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedOrganizationConnection.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedPostConnection.java
- src/main/java/com/echobox/api/linkedin/types/images/InitializeUpload.java
- src/main/java/com/echobox/api/linkedin/types/images/InitializeUploadRequestBody.java
- src/main/java/com/echobox/api/linkedin/types/posts/AdContext.java
- src/main/java/com/echobox/api/linkedin/types/posts/Content.java
- src/main/java/com/echobox/api/linkedin/types/posts/Distribution.java
- src/main/java/com/echobox/api/linkedin/types/posts/LifecycleStateInfo.java
- src/main/java/com/echobox/api/linkedin/types/posts/Post.java
- src/main/java/com/echobox/api/linkedin/types/posts/ViewContext.java
- src/main/java/com/echobox/api/linkedin/util/ValidationUtils.java
- Merge all PRs merged to dev_for_code_freeze
N/A
- Little. All changes are new functions
N/A
It should be merged as "Create a merge commit" instead of squashing to single one
> Merge code freeze branch to dev

- src/main/java/com/echobox/api/linkedin/types/posts/LifecycleStateInfo.java
- src/main/java/com/echobox/api/linkedin/types/posts/Post.java
- src/main/java/com/echobox/api/linkedin/types/posts/ReshareContext.java
- Add all properties of the `Post` schema 
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/posts-api#post-schema
Manually tested retrieving a post
> SL-3774 Add post schema properties

- src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/client/DefaultVersionedLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/client/LinkedInClient.java
- Change response type of requests in the client to have access to response headers
None - new functionality
Tested manually
> SL-4165 Change response type

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/version/Version.java
- Bump version to 4.0.0
- Update readme for the usage
- Update changelog
N/A
- Will release a new version of the SDK
N/A
> SL-3781 Update changelog & readme. Bump version to 4.0.0

- CHANGELOG.md
- pom.xml
Bump version for next release
N/A
N/A
N/A
> SL-3781 Bump version for next release

- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedVideoConnection.java
- Create `VersionedVideoConnection` class
> SL-4243 Create versioned video connection

- src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/client/DefaultVersionedLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/client/LinkedInClient.java
- src/main/java/com/echobox/api/linkedin/client/RequestType.java
- Introduce `RequestType` enum to delegate request methods in `WebRequestor`
Little - no change in functionality, just some code cleanup
> SL-4294 Clean up request types

- CHANGELOG.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/client/DefaultVersionedLinkedInClient.java
- src/main/java/com/echobox/api/linkedin/client/LinkedInClient.java
- src/main/java/com/echobox/api/linkedin/client/RequestType.java
- src/main/java/com/echobox/api/linkedin/client/WebRequestor.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedPostConnection.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedVideoConnection.java
- src/main/java/com/echobox/api/linkedin/exception/DefaultLinkedInExceptionMapper.java
- src/main/java/com/echobox/api/linkedin/types/videos/FinalizeUploadRequest.java
- src/main/java/com/echobox/api/linkedin/types/videos/InitializeUploadRequest.java
- src/main/java/com/echobox/api/linkedin/types/videos/InitializeUploadResponse.java
- src/main/java/com/echobox/api/linkedin/util/JsonUtils.java
- src/main/java/com/echobox/api/linkedin/util/ValidationUtils.java
- src/test/java/com/echobox/api/linkedin/types/video/VideoUploadTest.java
- src/test/java/com/echobox/api/linkedin/util/JsonUtilsTest.java
- src/test/resources/com.echobox.api.linkedin.jsonmapper/finalizeVideoUploadRequest.json
- src/test/resources/com.echobox.api.linkedin.jsonmapper/initializeVideoUploadRequest.json
- src/test/resources/com.echobox.api.linkedin.jsonmapper/initializeVideoUploadResponse.json
* Better support for non-default versioned month
* Add boolean support to JsonUtils
* Add support for video
N/A
Relase 4.1.0
N/A
> Release 4.1.0

- CHANGELOG.md
- pom.xml
- Bump version for next release
- Create next release header in CHANGELOG
> SL-4262 Prepare next release

- CHANGELOG.md
- pom.xml
- Bump version for next release
- Create next release header in CHANGELOG
> SL-4539 Prepare next release

- CHANGELOG.md
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedImageConnection.java
- src/main/java/com/echobox/api/linkedin/types/posts/ArticleContent.java
- src/main/java/com/echobox/api/linkedin/types/posts/CarouselCard.java
- src/main/java/com/echobox/api/linkedin/types/posts/CarouselContent.java
- src/main/java/com/echobox/api/linkedin/types/posts/Content.java
- src/main/java/com/echobox/api/linkedin/types/posts/Distribution.java
- src/main/java/com/echobox/api/linkedin/types/posts/MediaContent.java
- src/main/java/com/echobox/api/linkedin/types/posts/MultiImageContent.java
- src/main/java/com/echobox/api/linkedin/types/posts/PollContent.java
- src/main/java/com/echobox/api/linkedin/types/posts/Post.java
- src/main/java/com/echobox/api/linkedin/types/posts/ReshareContext.java
- src/main/java/com/echobox/api/linkedin/types/posts/TargetEntity.java
* Add constructors and builders for request/response objects
* Replace URN response of `uploadImage` method with full response 
> SL-4573 Add constructors and builders; Change upload image response

- CHANGELOG.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedImageConnection.java
- src/main/java/com/echobox/api/linkedin/types/posts/ArticleContent.java
- src/main/java/com/echobox/api/linkedin/types/posts/CarouselCard.java
- src/main/java/com/echobox/api/linkedin/types/posts/CarouselContent.java
- src/main/java/com/echobox/api/linkedin/types/posts/Content.java
- src/main/java/com/echobox/api/linkedin/types/posts/Distribution.java
- src/main/java/com/echobox/api/linkedin/types/posts/MediaContent.java
- src/main/java/com/echobox/api/linkedin/types/posts/MultiImageContent.java
- src/main/java/com/echobox/api/linkedin/types/posts/PollContent.java
- src/main/java/com/echobox/api/linkedin/types/posts/Post.java
- src/main/java/com/echobox/api/linkedin/types/posts/ReshareContext.java
- src/main/java/com/echobox/api/linkedin/types/posts/TargetEntity.java
- Add constructors and builders for request/response objects
- Replace URN response of `uploadImage` method with full response 
> Release 4.1.2

- CHANGELOG.md
- pom.xml
- Bump version
- Update CHANGELOG
> SL-4595 Prepare next release

- CHANGELOG.md
- README.md
- pom.xml
- Bump version
- Update changelog
> SL-4617 Prepare release 4.2.0

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedImageConnection.java
- src/main/java/com/echobox/api/linkedin/types/images/ImageDetails.java
- src/main/java/com/echobox/api/linkedin/types/posts/Post.java
* Add support to retrieve image details from LinkedIn
* Extend `Post` object to include image details mapping
* Add helper methods to `Post` to extract title, description and image URLs
Tested manually
> Release 4.2.0

- CHANGELOG.md
- pom.xml
- Bump version
- Update CHANGELOG
> SL-4617 Prepare next release

- CHANGELOG.md
- src/main/java/com/echobox/api/linkedin/types/posts/AdContext.java
- src/main/java/com/echobox/api/linkedin/types/posts/LifecycleStateInfo.java
- src/main/java/com/echobox/api/linkedin/types/posts/PollOption.java
- src/main/java/com/echobox/api/linkedin/types/posts/PollSettings.java
- src/main/java/com/echobox/api/linkedin/types/posts/ReshareContext.java
- Add missing LinkedIn annotations
> SL-4833 Add missing LinkedIn annotations

- CHANGELOG.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedVideoConnection.java
Allow video uploading from URLs in addition to file paths.
> Release 4.3.0

- CHANGELOG.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedVideoConnection.java
- src/main/java/com/echobox/api/linkedin/types/videos/InitializeUploadRequest.java
Added a new defaulting to false boolean `uploadThumbnail` in InitializeUploadRequest
Updated the methods to reflect the changes:
* getVideoURN()
* uploadVideoFromFile()
* uploadVideoFromURL()
This boolean will indicate if a thumbnail image should be shown for the video if there is a manually uploaded one.
N/A
N/A
N/A
> SL-5153 Add uploadThumbnail to InitializeUploadRequest

- CHANGELOG.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedVideoConnection.java
- src/main/java/com/echobox/api/linkedin/types/videos/InitializeUploadRequest.java
Add a flag to note that we want to upload a thumbnail image along with the video
N/A
N/A
N/A
> Release 4.3.1

- CHANGELOG.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/connection/v2/AssetsConnection.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/UploadHelper.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedImageConnection.java
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedVideoConnection.java
- src/main/java/com/echobox/api/linkedin/types/videos/InitializeUploadResponse.java
* Added thumbnailUploadUrl field to InitializeUploadResponse so we can use it to upload the thumbnail image for a video.
* Created UploadHelper class containing tools for converting files to bytes and uploading files to LinkedIn
* Refactoring
N/A
N/A
Tested by running the app locally and successfully shared a video to Linked with a thumbnail image
> Release 4.4.0

- CHANGELOG.md
- pom.xml
Bump version after release
N/A
N/A
N/A
N/A
> SL-5263 Bump version after release

- CHANGELOG.md
* Updated the changelog description
N/A
N/A
N/A
> GH-314 Update changelog

- CHANGELOG.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedVideoConnection.java
- src/main/java/com/echobox/api/linkedin/types/videos/VideoDetails.java
*  Added support to retrieve video details from LinkedIn
N/A
N/A
N/A
> Release 4.4.2

- CHANGELOG.md
Added changelog
Not Applicable
None
None
> GH-316 Added changelog

- CHANGELOG.md
- pom.xml
Update to 4.4.5 post release with work in progress
N/A
n/a
> Update post release

- CHANGELOG.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/connection/versioned/VersionedOrganizationConnection.java
Update version post release.
N/A
None
None
> SL-6725 Post release

- CHANGELOG.md
- src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java
Changed the log level of Request and response from debug to trace.
Version number will be changed post release
Added to the Changelog
Minimal as all it is is changing loglevels
Run tests
> SL-9055 Change Request and response log level message from debug to trace

- CHANGELOG.md
- README.md
- pom.xml
> SL-9269 - Release version 4.5.1

- CHANGELOG.md
This line should only have been added after the release of 4.5.1
This makes the master release cleaner.
None
> SL-9269 - remove work in progress section in changelog.

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/client/DefaultWebRequestor.java
Release version 4.5.1
Contains dependency updates and logging changes (reduces the logging severity).
> Release version 4.5.1

- CHANGELOG.md
- README.md
- pom.xml
Next release version so that the correct snapshot gets updated.
> SL-9269 - Next release version - 4.5.2

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/types/LinkedInURNIdType.java
- src/main/java/com/echobox/api/linkedin/types/posts/Post.java
- src/main/java/com/echobox/api/linkedin/types/urn/URNEntityType.java
See individual commits/PRs and CHANGELOG.
> Release version 4.6.0

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/connection/OrganizationConnection.java
See commits included.
Changelog updated
The default API version has been updated.
Do Not do a Squash and Merge
> Release 6.0.1

- .circleci/config.yml
- CHANGELOG.md
- README.md
- buildscripts/mvn_verify.sh
- pom.xml
See commits included.
Changelog updated
The build image has been updated
> Release 6.0.2

- .circleci/config.yml
- CHANGELOG.md
- README.md
- pom.xml
See commits included.
Changelog updated
The build image has been updated
> Release 7.0.0

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/echobox/api/linkedin/client/DefaultLinkedInClient.java
> Release 8.0.1
